# Generated by Django 5.2.5 on 2026-06-21 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(blank=True, max_length=50)),
                ('channel_name', models.CharField(blank=True, max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
                ('notify_tasks', models.BooleanField(default=True)),
                ('notify_meetings', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
