# Generated by Django 5.2.5 on 2026-06-15 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_due', 'Task Due Soon'), ('task_completed', 'Task Completed'), ('project_update', 'Project Update'), ('meeting_reminder', 'Meeting Reminder'), ('meeting_created', 'Meeting Created'), ('document_upload', 'Document Uploaded'), ('general', 'General')], default='general', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_assigned', models.BooleanField(default=True)),
                ('task_due', models.BooleanField(default=True)),
                ('task_completed', models.BooleanField(default=True)),
                ('project_update', models.BooleanField(default=True)),
                ('meeting_reminder', models.BooleanField(default=True)),
                ('meeting_created', models.BooleanField(default=True)),
                ('document_upload', models.BooleanField(default=False)),
                ('email_task_assigned', models.BooleanField(default=True)),
                ('email_task_due', models.BooleanField(default=True)),
                ('email_meeting_reminder', models.BooleanField(default=True)),
                ('email_meeting_created', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notif_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
